#!/bin/bash
#$ -N batch
#$ -pe smp 1
#$ -q long
#$ -cwd
mpirun -np $NSLOTS python /afs/crc.nd.edu/user/p/pmehta1/ising-monte-carlo/spins.py -n 20 -s 20000000 -i 3 -t 1.41554482759 -w magnetization/size-20/temp-3
