#!/bin/bash
#$ -N batch
#$ -pe smp 1
#$ -q long
#$ -cwd
python /afs/crc.nd.edu/user/p/pmehta1/ising-monte-carlo/spins.py -n 1000 -s 1000000000 -i 18 -t 2.82326896552 -w magnetization/size-1000/temp-18
