#!/bin/bash
#$ -N batch
#$ -pe smp 1
#$ -q long
#$ -cwd
python /afs/crc.nd.edu/user/p/pmehta1/ising-monte-carlo/spins.py -n 1000 -s 1000000000 -i 13 -t 2.35402758621 -w magnetization/size-1000/temp-13
