#!/bin/bash
#$ -N batch
#$ -pe smp 1
#$ -q long
#$ -cwd
mpirun -np $NSLOTS python /afs/crc.nd.edu/user/p/pmehta1/ising-monte-carlo/spins.py -n 50 -s 50000000 -i 2 -t 1.32169655172 -w magnetization/size-50/temp-2
